### PR TITLE
add xcode configuration to step configuration

### PR DESCRIPTION
**Pull request by vincentsaluzzo**

### CODE REVIEW

**Comment by viktorbenei** [comment]
Thanks for the PR! 

One question : why do you think the configuration should be added? 

It certainly should not be required, might be an optional input, but you can manage the configuration with your Scheme, so this option seems to be redundant. This is actually the reason why we did not include it in the first place.

**Comment by viktorbenei** [comment]
But of course if there's an actual use case for adding it we would certainly consider it.

**Comment by vincentsaluzzo** [comment]
In our case, Configuration and scheme is used for different things: 

- We use scheme to manage server side environment (When our app are used in staging environment)
- We use configuration to have specific build settings (AdHoc provisioning profile for tester and AppStore when deploy to the AppStore)

So we absolutely need the configuration parameter to Xcode Build.
But of course, this parameter could be totally optional and it's a mistake from my side. But i've made this modification in few time and I have no idea for how make this parameters optional or on debug/release by default.

**Comment by vincentsaluzzo** [comment]
Also, configuration is a part of Xcode build tool and don't allow people to use it in CI configuration could frustrate.

**Comment by viktorbenei** [comment]
That's completely reasonable @vincentsaluzzo but does it happen that you want to Archive with Debug configuration, or any other configuration rather than Release? I'm just curious in your setup, as we never really had the need to use configurations instead of Schemes.

> Also, configuration is a part of Xcode build tool and don't allow people to use it in CI configuration could frustrate.

I agree with this, but as in Xcode.app only Schemes are exposed it made sense for us to not to include the configuration option, as most of the iOS developers are not even familiar with it, as it's not available on the GUI, at least not as easily as Schemes.

**Comment by vincentsaluzzo** [comment]
Yes of course. I will trying to explain how we use this feature.

For a big project, an international application, we use target to differentiate application by country. Localizable-feature of Xcode aren't suffisant in our case and client want to mutualize source code of each app but without a same bundle-id and a same configuration in iTunes Connect (One app for France, One app for United States, etc.)

To complexify this architecture, client have multiple server environment (Production, staging, development) and would have each environment available for each specific-country application.

So, we have, a 2D configuration aspect (functional server side and client build configuration). We managed this by: 
- a Scheme (and target) by a country
- a Configuration by server environment

Configuration allow us to define build variable (prefix header) and we could get this variable when compiling to easily find in our code the environment we want.

Did you understand why we absolutely need configuration ?

**Comment by viktorbenei** [comment]
Thanks for the explanation @vincentsaluzzo ! It's always interesting to hear about how other iOS developers use the tools and options available for them 😊

We're happy to accept this PR if you modify it so that the Configuration is not required to be defined. There's another PR which introduces `xctool` support, we'll merge that first, so you'll probably have to update your PR to fix the merge conflict.

**Comment by vincentsaluzzo** [comment]
Got it !

**Comment by viktorbenei** [comment]
Just merged the other PR, please make the Configuration input and optional parameter & fix the merge conflict and you're good to go, we'll merge this PR in no time 😉

**Comment by vincentsaluzzo** [comment]
Done, you can review PR right now ;)

**Comment by viktorbenei** [comment]
Thanks for your contribution! 😊

**Pull request merged**
